"""Translate template UI text without rewriting rendered user data or form values."""
import re

from jinja2.ext import Extension
from jinja2.lexer import Token


class StaticUiTranslation(Extension):
    def filter_stream(self, stream):
        for token in stream:
            if token.type != "data" or not re.search(r"[\u3400-\u9fff]", token.value):
                yield token
                continue
            # Only trusted literal template HTML is marked safe by ui_static.
            for kind, value in [
                ("variable_begin", "{{"), ("string", token.value),
                ("pipe", "|"), ("name", "ui_static"), ("variable_end", "}}"),
            ]:
                yield Token(token.lineno, kind, value)


EMS_VI_TRANSLATIONS = {
    "選擇查詢方式（四選一）": "Chọn một trong bốn cách tra cứu",
    "只需填寫所選方式的欄位，不會與其他方式混用。": "Chỉ nhập các trường của cách đã chọn; không kết hợp với các cách khác.",
    "查詢方式": "Cách tra cứu",
    "單月": "Một tháng",
    "月份區間": "Khoảng tháng",
    "整年": "Cả năm",
    "查詢年份": "Năm tra cứu",
    "請選擇年份": "Chọn năm",
    "套用查詢": "Áp dụng tra cứu",
    "起始與結束月份需一起填寫，包含首尾月份，可跨年度。": "Nhập cả tháng bắt đầu và kết thúc; bao gồm hai tháng này và có thể qua nhiều năm.",
    "依資料所屬月份查詢，不是依送出時間或更新時間查詢。": "Tra cứu theo tháng của dữ liệu, không theo thời gian gửi hoặc cập nhật.",
    "查詢尚未執行，請修正上方條件。": "Chưa thực hiện tra cứu; vui lòng sửa điều kiện phía trên.",
    "目前結果：": "Kết quả hiện tại:",
    "匯出目前結果": "Xuất kết quả hiện tại",
    "修改條件後請按「套用查詢」；下方資料與匯出皆以目前結果為準。": "Sau khi sửa điều kiện, nhấn Áp dụng tra cứu; bảng bên dưới và tệp xuất đều theo kết quả hiện tại.",
    "此範圍沒有填報紀錄，請核對下方已有紀錄的月份。": "Không có bản ghi trong khoảng này; hãy kiểm tra các tháng có dữ liệu bên dưới.",
    "已有填報紀錄的月份": "Các tháng có bản ghi khai báo",
    "目前尚無任何填報紀錄。": "Hiện chưa có bản ghi khai báo nào.",
    "查詢條件混用了不同方式，請先選擇一種查詢方式。": "Điều kiện đang kết hợp nhiều cách tra cứu; vui lòng chọn một cách.",
    "請選擇有效的查詢月份。": "Vui lòng chọn tháng tra cứu hợp lệ.",
    "請選擇有效的查詢年份。": "Vui lòng chọn năm tra cứu hợp lệ.",
    "查詢方式不正確，請重新選擇。": "Cách tra cứu không hợp lệ; vui lòng chọn lại.",
    "全體點位概況（不受篩選影響）": "Tổng quan tất cả điểm (không áp dụng bộ lọc)",
    "以下條件可一起使用，只顯示同時符合所有條件的點位；留空或選「全部」表示不限制。": "Có thể kết hợp các điều kiện dưới đây; chỉ hiển thị điểm thỏa tất cả điều kiện. Để trống hoặc chọn Tất cả để không giới hạn.",
    "搜尋文字會比對點位名稱、路徑、說明及顯示名稱，任一欄符合即可。": "Từ khóa tìm trong tên điểm, đường dẫn, mô tả và tên hiển thị; chỉ cần một trường khớp.",
    "套用篩選": "Áp dụng bộ lọc",
    "清除全部篩選": "Xóa tất cả bộ lọc",
    "未限制條件，顯示全部點位。": "Không giới hạn điều kiện; hiển thị tất cả điểm.",
    "修改條件後請按「套用篩選」；匯出包含目前條件的所有頁面。": "Sau khi sửa điều kiện, nhấn Áp dụng bộ lọc; tệp xuất bao gồm tất cả các trang khớp điều kiện hiện tại.",
    "批次修改（僅限勾選的點位）": "Sửa hàng loạt (chỉ các điểm đã đánh dấu)",
    "請減少篩選條件，或按「清除全部篩選」查看全部點位。": "Hãy giảm điều kiện hoặc nhấn Xóa tất cả bộ lọc để xem mọi điểm.",
    "選擇要填寫的月份": "Chọn tháng cần khai báo",
    "選好月份後按「切換月份」，下方表格才會載入該月份資料。": "Sau khi chọn tháng, nhấn Đổi tháng để tải dữ liệu tháng đó vào bảng bên dưới.",
    "套用分析月份": "Áp dụng tháng phân tích",
    "分析月份會套用到金額、填報進度、能源占比與區域排名；趨勢圖固定顯示最近 12 個有資料的月份。": "Tháng phân tích áp dụng cho số tiền, tiến độ khai báo, tỷ trọng năng lượng và xếp hạng khu vực; biểu đồ xu hướng luôn hiển thị 12 tháng gần nhất có dữ liệu.",
    "EMS 公用點位設定": "Cấu hình điểm tiện ích EMS",
    "EMS 點位設定": "Cấu hình điểm EMS",
    "編輯 EMS 點位設定": "Chỉnh sửa cấu hình điểm EMS",
    "來源點位會在部署後自動比對版本；管理員填寫的上下限與 EMS 分類不會被來源同步覆蓋。": "Phiên bản điểm nguồn được kiểm tra tự động sau khi triển khai; đồng bộ nguồn không ghi đè giới hạn và phân loại EMS do quản trị viên nhập.",
    "點位版本": "Phiên bản điểm",
    "尚未匯入點位版本": "Chưa nhập phiên bản điểm",
    "點位摘要": "Tổng quan điểm",
    "公用點位": "Điểm tiện ích",
    "本地 SQLite 點位快照": "Bản chụp điểm trong SQLite",
    "啟用監控": "Bật giám sát",
    "新點位預設啟用": "Điểm mới được bật mặc định",
    "已設定門檻": "Đã đặt ngưỡng",
    "至少設定上限或下限": "Đã đặt ít nhất một giới hạn",
    "尚未完成分類": "Chưa hoàn tất phân loại",
    "等待管理員補充資料": "Chờ quản trị viên bổ sung thông tin",
    "來源資料問題": "Vấn đề dữ liệu nguồn",
    "缺值、重複或來源失效": "Thiếu dữ liệu, trùng lặp hoặc nguồn không còn hợp lệ",
    "搜尋與篩選": "Tìm kiếm và lọc",
    "搜尋點位": "Tìm điểm",
    "監控狀態": "Trạng thái giám sát",
    "全部": "Tất cả",
    "監控中": "Đã bật giám sát",
    "不監控": "Không giám sát",
    "能源類別": "Nhóm năng lượng",
    "全部類別": "Tất cả nhóm",
    "資料狀態": "Trạng thái dữ liệu",
    "全部狀態": "Tất cả trạng thái",
    "分類完成": "Đã phân loại",
    "尚未分類": "Chưa phân loại",
    "未分類": "Chưa phân loại",
    "來源有問題": "Nguồn có vấn đề",
    "尚未設定門檻": "Chưa đặt ngưỡng",
    "來源已不存在": "Nguồn không còn tồn tại",
    "全部區域": "Tất cả khu vực",
    "清除": "Xóa bộ lọc",
    "筆已選取": "điểm đã chọn",
    "批次能源類別": "Nhóm năng lượng hàng loạt",
    "批次設定能源類別…": "Đặt nhóm năng lượng hàng loạt…",
    "套用類別": "Áp dụng nhóm",
    "停止監控": "Tắt giám sát",
    "全選本頁": "Chọn tất cả trên trang",
    "外部 Id": "ID bên ngoài",
    "監控": "Giám sát",
    "測量類型": "Loại đo lường",
    "狀態": "Trạng thái",
    "操作": "Thao tác",
    "選取點位": "Chọn điểm",
    "（空白）": "(trống)",
    "來源待確認": "Cần xác nhận nguồn",
    "缺少門檻": "Thiếu ngưỡng",
    "設定完成": "Đã cấu hình",
    "編輯": "Chỉnh sửa",
    "目前篩選條件沒有符合的點位。": "Không có điểm phù hợp với bộ lọc hiện tại.",
    "顯示第": "Hiển thị",
    "筆，共": "bản ghi, tổng",
    "共 0 筆": "Tổng 0 bản ghi",
    "筆・": "bản ghi ·",
    "筆": "bản ghi",
    "每頁": "Mỗi trang",
    "上一頁": "Trang trước",
    "下一頁": "Trang sau",
    "關閉": "Đóng",
    "來源點位資料（唯讀）": "Thông tin điểm nguồn (chỉ đọc)",
    "資料來源": "Nguồn dữ liệu",
    "監控與門檻": "Giám sát và ngưỡng",
    "是否監控": "Bật giám sát",
    "啟用此點位監控": "Bật giám sát điểm này",
    "未設定": "Chưa thiết lập",
    "尚未設定": "Chưa thiết lập",
    "告警等級": "Mức cảnh báo",
    "告警判斷值": "Giá trị đánh giá cảnh báo",
    "累積表值通常使用「每次收集差值」。": "Giá trị bộ đếm tích lũy thường dùng chênh lệch giữa hai lần thu thập.",
    "連續異常次數": "Số lần bất thường liên tiếp",
    "連續幾次收集超限才告警。": "Số lần thu thập vượt giới hạn liên tiếp để phát cảnh báo.",
    "告警解除緩衝（Deadband）": "Vùng đệm xóa cảnh báo (Deadband)",
    "單位與點位相同；設為 0 表示回到界限內便解除。": "Cùng đơn vị với điểm; đặt 0 để xóa cảnh báo khi giá trị trở về trong giới hạn.",
    "EMS 分類": "Phân loại EMS",
    "EMS 顯示名稱": "Tên hiển thị EMS",
    "工程單位": "Đơn vị đo",
    "設備／系統": "Thiết bị / hệ thống",
    "數值性質": "Kiểu giá trị",
    "統計方式": "Phương pháp thống kê",
    "流向": "Hướng dòng",
    "備註": "Ghi chú",
    "取消": "Hủy",
    "儲存設定": "Lưu cấu hình",
    "目前每 ${interval} 分鐘收集一次；連續幾次超限才告警。": "Hiện thu thập mỗi ${interval} phút; cảnh báo sau số lần vượt giới hạn liên tiếp đã đặt.",
    "下限不可大於上限，請修正後再儲存。": "Giới hạn dưới không được lớn hơn giới hạn trên; vui lòng sửa trước khi lưu.",
    "請先選擇至少一個點位。": "Vui lòng chọn ít nhất một điểm.",
    "選取的點位不存在。": "Điểm đã chọn không tồn tại.",
    "請選擇要套用的能源類別。": "Vui lòng chọn nhóm năng lượng cần áp dụng.",
    "批次操作不正確。": "Thao tác hàng loạt không hợp lệ.",
    "找不到指定的 EMS 點位。": "Không tìm thấy điểm EMS đã chọn.",
    "告警緩衝值不可小於零。": "Vùng đệm cảnh báo không được nhỏ hơn 0.",
    "告警緩衝值": "Vùng đệm cảnh báo",
    "連續異常次數必須介於 1 到 168 次。": "Số lần bất thường liên tiếp phải là số nguyên từ 1 đến 168.",
    "必須是有效數字。": " phải là số hợp lệ.",
    "必須是有限數字。": " phải là số hữu hạn.",
    "選項不正確。": ": lựa chọn không hợp lệ.",
    "選項不存在。": ": lựa chọn không tồn tại.",
    "點位 ": "Điểm ",
    " 的 EMS 設定已儲存。": ": đã lưu cấu hình EMS.",
    "已為 ": "Đã áp dụng cho ",
    " 個點位完成「": " điểm: «",
    "」。": "».",
    "設定能源類別": "Đặt nhóm năng lượng",
    "瞬時值": "Giá trị tức thời",
    "累積表值": "Giá trị bộ đếm tích lũy",
    "計算值": "Giá trị tính toán",
    "平均": "Trung bình",
    "期末減期初": "Cuối kỳ trừ đầu kỳ",
    "加總": "Tổng",
    "最大值": "Giá trị lớn nhất",
    "最小值": "Giá trị nhỏ nhất",
    "最後值": "Giá trị cuối cùng",
    "運轉時間": "Thời gian vận hành",
    "不統計": "Không thống kê",
    "輸入": "Đầu vào",
    "消耗": "Tiêu thụ",
    "生產": "Sản xuất",
    "輸出": "Đầu ra",
    "回收": "Thu hồi",
    "排放": "Xả thải",
    "提示": "Thông tin",
    "警告": "Cảnh báo",
    "嚴重": "Nghiêm trọng",
    "原始讀值": "Giá trị đọc gốc",
    "每次收集差值": "Chênh lệch mỗi lần thu thập",
    "變化率": "Tốc độ thay đổi",
    "電力": "Điện",
    "用水": "Nước sử dụng",
    "廢水": "Nước thải",
    "蒸汽": "Hơi nước",
    "天然氣": "Khí tự nhiên",
    "壓縮空氣": "Khí nén",
    "氮氣": "Khí nitơ",
    "冰水": "Nước lạnh",
    "冷卻水": "Nước làm mát",
    "煤": "Than",
    "生質燃料": "Nhiên liệu sinh khối",
    "產量": "Sản lượng",
    "環境指標": "Chỉ số môi trường",
    "其他": "Khác",
    "瞬時流量": "Lưu lượng tức thời",
    "累積流量": "Lưu lượng tích lũy",
    "功率": "Công suất",
    "累積能源": "Năng lượng tích lũy",
    "壓力": "Áp suất",
    "溫度": "Nhiệt độ",
    "露點": "Điểm sương",
    "液位": "Mức chất lỏng",
    "導電度": "Độ dẫn điện",
    "電流": "Dòng điện",
    "電壓": "Điện áp",
    "運轉狀態": "Trạng thái vận hành",
    "公噸": "Tấn",
    "來源存在": "Nguồn tồn tại",
    "更新者": "Người cập nhật",
    "來源說明": "Mô tả nguồn",
    "暫無日誌記錄。": "Chưa có nhật ký.",
    "每月能源費用趨勢圖": "Biểu đồ xu hướng chi phí năng lượng hàng tháng",
    "最近 15 筆系統操作記錄": "15 thao tác hệ thống gần nhất",
    "按 ": "Nhấn ",
    " 複製選取的 Excel 資料。": " để sao chép dữ liệu Excel đã chọn.",
    "，資料會依照 Excel 的列與欄自動填入。": "; dữ liệu sẽ tự động điền theo hàng và cột trong Excel.",
    "備份失敗:": "Sao lưu thất bại:",
    "目前尚未被指派可填寫的能源種類或單位，無法送出。": "Bạn chưa được cấp quyền nhập loại năng lượng hoặc đơn vị nên không thể gửi.",
}
